### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by pombredanne** [paultag/python-opensource#1]
@paultag 
You may have strong feeling about licensing: so feel free to ignore this request entirely.
I was wondering if an LGPL could not make more sense for a small library like this?
Such that I could reuse it in https://github.com/nexB/scancode-toolkit which is Apache-licensed?
In all cases this is not a lot of code, so reimplementing if needed would not be a huge undertaking.

Cordially
Philippe

**Comment by paultag** [comment]
@pombredanne the point is to allow interoperability; so I've re-licensed it to MIT/Expat and updated the cheeseshop and Git. Thanks!

**Comment by pombredanne** [comment]
@paultag Thank you my lord!
